version: "3"

services:
  web:
    build: .

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    image: node:20

    ports:
      - 3000:3000

    environment:
      DATABASE_URL: "postgres://postgres:ASDFarinasjkn324423lknsma4@database-1.c9yoik2qylmi.us-east-1.rds.amazonaws.com:5432/database-1"
      ADMINJS_COOKIE_PASSWORD: "flksdjflfSDGasfFSDFSADfsdfsadFSFas"
      JWT_KEY: "sdafjklsn3rqfwenammavnbbrra"
      NODE_ENV: "development"
